[package]
name = "fhistory"
version = "0.1.0"
authors = ["Paul Asmuth <paul@asmuth.com>"]
repository = "https://github.com/asmuth/fhistory"

[dependencies]
rust-crypto = "*"
getopts = "*"
regex = "*"
walkdir = "*"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
